name: Build and install modules

on:
  push:
    branches:
      - 'intel/**'
      - 'intel-test/**'
    tags:
      - 'intel-*'
    paths:
      - '.github/workflows/modules.yml'
      - 'Makefile'
      - 'build/**'
      - 'drivers/**'
      - 'include/**'

  pull_request:
    branches:
      - 'intel/**'
      - 'intel-test/**'
    paths:
      - '.github/workflows/modules.yml'
      - 'Makefile'
      - 'build/**'
      - 'drivers/**'
      - 'include/**'

  workflow_dispatch:

jobs:
  modules:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - vendor: centos
            release: '8.2.2004'
            pkg: rpm
          - vendor: centos
            release: '8.3.2011'
            pkg: rpm
          - vendor: rockylinux
            release: '8'
            pkg: rpm
          - vendor: rockylinux
            release: '8.4'
            pkg: rpm
          - vendor: rockylinux
            release: '8.6'
            pkg: rpm
          - vendor: rockylinux
            release: '8.8'
            pkg: rpm
          - vendor: rockylinux
            release: '9'
            pkg: rpm
          - vendor: rockylinux
            release: '9.0'
            pkg: rpm
          - vendor: rockylinux
            release: '9.2'
            pkg: rpm
          - vendor: ubuntu
            release: '20.04'
            pkg: deb
          - vendor: ubuntu
            release: '22.04'
            pkg: deb

    container:
      image: ghcr.io/ofs/linux-dfl-backport/${{ matrix.vendor }}-kernel-devel:${{ matrix.release }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Makefile derives the package version from git describe, which will
        # fall back to the commit hash if no tagged commits are available.
        # Since Debian package versions must start with a number, this will
        # fail the build when the hash does not start with a decimal digit.
        fetch-depth: 0
        fetch-tags: true

    # The owner of the workspace directory may not match the owner of the
    # git process in the container, which triggers git's ownership detection.
    - name: Work around git's ownership detection
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Build modules
      run: make KERNEL="$(basename /lib/modules/*)"

    - name: Install modules
      run: make KERNEL="$(basename /lib/modules/*)" install

    - name: Upload modules
      uses: actions/upload-artifact@v3
      with:
        name: linux-dfl-backport-modules-${{ matrix.vendor }}-${{ matrix.release }}-${{ github.run_id }}
        path: /lib/modules/*/extra/
        if-no-files-found: error
